name: Deploy to Staging
on:
  push:
    branches: ['main']

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Redeploy everything to Staging
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PVT_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: SSH and Deploy to EC2
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i ssh_key ubuntu@3.108.220.26 << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd bms-deploy-cicd/

            git pull origin main

            # Ensure pnpm and pm2 are available (skip if already installed)
            command -v pnpm >/dev/null 2>&1 || npm install -g pnpm
            command -v pm2 >/dev/null 2>&1 || npm install -g pm2

            pnpm install
            pnpm run build

            pm2 restart fe-server-dev
            pm2 restart http-server-dev 
            pm2 restart ws-server-dev
          EOF









name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts
          chmod 700 ~/ssh_key
          ssh -i ~/ssh_key root@64.227.147.124 -t "
            cd week-25-ci-next-app/ &&
            git pull origin main &&
            export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin &&
            npm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-sever &&
            pm2 restart http-sever &&
            pm2 restart ws-sever
          "
