name: Deploy to Staging
on:
  push:
    branches:
      - main

jobs:
  uses:ubuntu-latest:
  redeploy_everything:
    name: Redeploy everything to Staging
    steps:
      - name: SSH into server
      - run: |
          echo ${{ secrets.SSH_PVT_KEY }} &> ~/ssh_key
          ssh -i ~/ssh_key ubuntu@3.108.220.26
          cd bms-deploy-cicd/ && git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server-dev
          pm2 restart http-server-dev
          pm2 restart ws-server-dev