name: Deploy to Staging
on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Redeploy everything to Staging
    steps:
      - name: SSH into server
      - run: echo "Redeploying everything to Staging server"